
namespace rlf
{

#define RLF_TEXTUREFORMAT_TUPLE	\
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32A32_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32A32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32A32_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32A32_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R10G10B10A2_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R10G10B10A2_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R10G10B10A2_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R11G11B10_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_UNORM_SRGB) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(D32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R16_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(D16_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(A8_UNORM) \


#define RLF_TEXTUREFORMAT_ENTRY(name) name,
enum class TextureFormat
{
	RLF_TEXTUREFORMAT_TUPLE
	_Count
};
#undef RLF_TEXTUREFORMAT_ENTRY

#define RLF_TEXTUREFORMAT_ENTRY(name) #name,
static const char* TextureFormatName[] = {
	RLF_TEXTUREFORMAT_TUPLE
};
#undef RLF_TEXTUREFORMAT_ENTRY

#define RLF_TEXTUREFORMAT_ENTRY(name) DXGI_FORMAT_##name,
static DXGI_FORMAT D3DTextureFormat[] = {
	RLF_TEXTUREFORMAT_TUPLE
};
#undef RLF_TEXTUREFORMAT_ENTRY

} // namespace rlf
