
namespace rlf
{

#define RLF_TEXTUREFORMAT_TUPLE	\
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32A32_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32A32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32A32_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32A32_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32B32_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16B16A16_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G32_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32G8X24_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(D32_FLOAT_S8X24_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_FLOAT_X8X24_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(X32_TYPELESS_G8X24_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R10G10B10A2_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R10G10B10A2_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R10G10B10A2_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R11G11B10_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_UNORM_SRGB) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8B8A8_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16G16_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(D32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R32_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R24G8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(D24_UNORM_S8_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R24_UNORM_X8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(X24_TYPELESS_G8_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R16_FLOAT) \
	RLF_TEXTUREFORMAT_ENTRY(D16_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R16_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R16_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(R8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8_UINT) \
	RLF_TEXTUREFORMAT_ENTRY(R8_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R8_SINT) \
	RLF_TEXTUREFORMAT_ENTRY(A8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R1_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R9G9B9E5_SHAREDEXP) \
	RLF_TEXTUREFORMAT_ENTRY(R8G8_B8G8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(G8R8_G8B8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(BC1_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(BC1_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(BC1_UNORM_SRGB) \
	RLF_TEXTUREFORMAT_ENTRY(BC2_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(BC2_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(BC2_UNORM_SRGB) \
	RLF_TEXTUREFORMAT_ENTRY(BC3_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(BC3_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(BC3_UNORM_SRGB) \
	RLF_TEXTUREFORMAT_ENTRY(BC4_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(BC4_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(BC4_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(BC5_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(BC5_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(BC5_SNORM) \
	RLF_TEXTUREFORMAT_ENTRY(B5G6R5_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(B5G5R5A1_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(B8G8R8A8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(B8G8R8X8_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(R10G10B10_XR_BIAS_A2_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(B8G8R8A8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(B8G8R8A8_UNORM_SRGB) \
	RLF_TEXTUREFORMAT_ENTRY(B8G8R8X8_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(B8G8R8X8_UNORM_SRGB) \
	RLF_TEXTUREFORMAT_ENTRY(BC6H_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(BC6H_UF16) \
	RLF_TEXTUREFORMAT_ENTRY(BC6H_SF16) \
	RLF_TEXTUREFORMAT_ENTRY(BC7_TYPELESS) \
	RLF_TEXTUREFORMAT_ENTRY(BC7_UNORM) \
	RLF_TEXTUREFORMAT_ENTRY(BC7_UNORM_SRGB) \


#define RLF_TEXTUREFORMAT_ENTRY(name) name,
enum class TextureFormat
{
	Invalid,
	RLF_TEXTUREFORMAT_TUPLE
	_Count
};
#undef RLF_TEXTUREFORMAT_ENTRY

#define RLF_TEXTUREFORMAT_ENTRY(name) #name,
static const char* TextureFormatName[] = {
	"<Invalid>",
	RLF_TEXTUREFORMAT_TUPLE
};
#undef RLF_TEXTUREFORMAT_ENTRY

#define RLF_TEXTUREFORMAT_ENTRY(name) DXGI_FORMAT_##name,
static DXGI_FORMAT D3DTextureFormat[] = {
	DXGI_FORMAT_UNKNOWN,
	RLF_TEXTUREFORMAT_TUPLE
};
#undef RLF_TEXTUREFORMAT_ENTRY

} // namespace rlf
